In [1]:
import pandas as pd

In [4]:
df =pd.read_csv("Pokemon.csv")

In [7]:
df.head()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,SpAtk,SpDef,Speed
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80

In [6]:
df.tail()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,SpAtk,SpDef,Speed
195,196,Espeon,Psychic,NaN,525,65,65,60,130,95,110
196,197,Umbreon,Dark,NaN,525,95,65,110,60,130,65
197,198,Murkrow,Dark,Flying,405,60,85,42,85,42,91
198,199,Slowking,Water,Psychic,490,95,75,80,100,110,30
199,200,Misdreavus,Ghost,NaN,435,60,60,60,85,85,85

In [9]:
df.shape

(200, 11)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Number   200 non-null    int64
 1   Name     200 non-null    object
 2   Type1    200 non-null    object
 3   Type2    90 non-null     object
 4   Total    200 non-null    int64
 5   HP       200 non-null    int64
 6   Attack   200 non-null    int64
 7   Defense  200 non-null    int64
 8   SpAtk    200 non-null    int64
 9   SpDef    200 non-null    int64
 10  Speed    200 non-null    int64
dtypes: int64(8), object(3)
memory usage: 17.3+ KB

In [11]:
df.columns

Index(['Number', 'Name', 'Type1', 'Type2', 'Total', 'HP', 'Attack', 'Defense',
       'SpAtk', 'SpDef', 'Speed'],
      dtype='object')

AttributeError: ignored

In [19]:
df